### ISSUE TITLE
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'

### ISSUE THREAD

**Issue by krishdevdb** [krishdevdb/krishdevdb.github.io#1]
## Bug

![Bug](https://user-images.githubusercontent.com/76587897/118089260-c8a3e900-b3e5-11eb-822b-2bb3bb722f50.PNG)

## Solution

This looks like something that can be fixed by first-time contributors to this repository. If you have already contributed to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Fork This Repository
- Delete `.nojekyll`
- Commit `:bug: Fix #1` with Message: `:fire: Remove .nojekyll For Error with Permissions-Policy header`

If you have any questions about how to resolve this issue or the contributing process in general, tell us here.

If you are interested in addressing this issue, reply here and we can assign the issue to you.

**Comment by slayer321** [comment]
hey, I will like to take this issue ....... 
the only thing that needs to be done is we have to remove the `.nojekyll` file?

**Comment by krishdevdb** [comment]
Yes, @slayer321
